import re
import json
from urllib.request import urlopen, Request
import toml

MAJOR_VERSION_TAG_RE = re.compile(r"refs/tags/((?:release/)?v\d+)")

SCOPE = [
    # Generally "v<n>" tags
    "actions/checkout",
    "actions/setup-python",
    "actions/upload-artifact",
    "actions/download-artifact",
    "astral-sh/setup-uv",
    # This one is a little different; release/v1 is a branch
    # "pypa/gh-action-pypi-publish",
]

def regen():
    latest_versions = {}

    for i in SCOPE:
        url = f"https://api.github.com/repos/{i}/git/matching-refs/tags/"
        data = urlopen(Request(url, headers={"Accept": "application/vnd.github+json", "X-GitHub-Api-Version": "2022-11-28"})).read().decode()
        obj = json.loads(data)
        for tag_obj in obj:
            if m := MAJOR_VERSION_TAG_RE.fullmatch(tag_obj["ref"]):
                latest_versions[i] = m.group(1)

    with open("upgrade.toml", "w") as f:
        f.write("# Generated by upgrade_upgrade.py\n")
        f.write("\n")
        toml.dump(latest_versions, f)

if __name__ == "__main__":
    regen()
