name: Build
on:
  push:
    branches:
      - master
      - main
      - tmp-*
    tags:
      - v*
  pull_request:

env:
  UV_SYSTEM_PYTHON: 1

jobs:
  test:
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        python-version: ["3.11", "3.12", "3.13"]
        os: [macOS-latest, ubuntu-latest]

    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Set Up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python-version }}
      - uses: astral-sh/setup-uv@v3
      - name: Install
        run: |
          uv pip install ick
      - name: Test
        run: |
          git config --global user.name "Unit Test"
          git config --global user.email "example@example.com"
          make test
      - name: Lint
        run: |
          make lint
